### ISSUE TITLE
4k fractional scaling display support

### ISSUE THREAD

**Issue by jaro3** [google/mozc#514] opened 2021-07-18 02:28 UTC
On Gnome with Xorg fractional scaling (Nvidia) the input suggestion window is half invisible.  It doesn't expand properly to see all the choices to be able to choose the right one.....

**Comment by hiroyuki-komatsu** [comment] 2021-07-18 06:27
Hi, please let us know the following things to understand the issue more.

* Screenshots of the problem.
* The version of Mozc. You can get it by converting from "ばーじょん" (ba-jon) to the version string.
* Platform information (e.g. Ubuntu 20.4).
* Input method framework (e.g. Ibus, Fcitx, etc.).
* Whether this issue already happens or not.
* Steps to reproduce this issue, if you have.

Thank you,

**Comment by jaro3** [comment] 2021-07-18 13:20
![MVIMG_20210718_220845s](https://user-images.githubusercontent.com/12386887/126068556-69a84f1c-e109-4c46-96d6-0f46afa464fe.jpg)

**Comment by jaro3** [comment] 2021-07-18 13:21
Mozc-2.26.4416.102+24.10.oss
Arch Linux:
ibus-mozc-ut 2.26.4416.102.20210627-1  +  mozc-ut-common 2.26.4416.102.20210627-1
gnome-shell 1:40.2-1
mutter-x11-scaling 40.2.1-1
gnome-control-center-x11-scaling 40.0-2
xorg-server 1.20.12-1
nvidia-dkms-performance 470.42.01-4
kernel 5.12.0-pf1-1
display scale 150% or 125% in both cases
Reproduce: Install the modified mutter and gnome-control-center and scale anything else than 100% or 200%

**Comment by jaro3** [comment] 2021-07-18 13:23
also the mouse clicks lag after using this Japanese input method for a while and the system sometimes completely freezes (not the console, only gnome) mozc eating 100% cpu

**Comment by hiroyuki-komatsu** [comment] 2021-07-18 16:49
Thank you for the information.

Do you have the same issue on Mozc's GUI tools (mozc_tool)? Both this candidate window and the GUI tools use Qt.

For 100% CPU usage, do you always have the issue? Because it isn't reproducible on my environment, it's hard to investigate it.

(My next reply might be on the next weekend).

**Comment by jaro3** [comment] 2021-07-19 01:00
Mozc's GUI tools have no problems, it's only the input window....
Thank you in advance.

**Comment by hiroyuki-komatsu** [comment] 2021-07-25 12:05
The commit f76f5b1 tweaks the Qt attributes as well as the GUI tools.

Would you check if this change solves the scaling problem?

**Comment by jaro3** [comment] 2021-07-27 09:04
![IMG_20210727_175821](https://user-images.githubusercontent.com/12386887/127127294-0b3d6d1f-0573-4c38-b5d8-35f99af32f29.jpg)

**Comment by hiroyuki-komatsu** [comment] 2021-07-31 17:33
Thanks for the confirmation.
I will keep investigations.

Would you also make sure the following things just in case?
* File timestamp of `mozc_renderer`.
  + The default file path (on Ubuntu) is `/usr/lib/mozc/mozc_renderer`.
* Reboot of `mozc_renderer`.
  + After the command `killall mozc_renderer`, `mozc_renderer` will be rebooted automatically by the Ibus client.

Note, the version number (i.e. Mozc-2.26.4444..) comes from `mozc_server`, but this is a problem on `mozc_renderer`.
So I'd like to make sure  `mozc_renderer` is also updated with `mozc_server`.

**Comment by jaro3** [comment] 2021-08-01 01:54
ibus-mozc-ut 2.26.4444.102.20210725-1
mozc-ut-common 2.26.4444.102.20210725-1

stat /usr/lib/mozc/mozc_renderer
  File: /usr/lib/mozc/mozc_renderer
  Size: 1925832   	Blocks: 3768       IO Block: 4096   regular file
Device: 1ah/26d	Inode: 4176892     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-07-27 17:37:17.000000000 +0900
Modify: 2021-07-27 17:26:51.000000000 +0900
Change: 2021-07-27 17:37:17.605295683 +0900
 Birth: 2021-07-27 17:37:17.596295604 +0900
 
mozc_renderer is part of ibus-mozc-ut - all rebuilt from scratch, multiple reboots, symptoms same :-(
also tried to rebuilt dconf from scratch but no help....
Sometimes the input window gets overly big but the shape never change, always cut after a few rows....

**Comment by hiroyuki-komatsu** [comment] 2021-08-08 08:58
Thank you for the confirmation.

Would you also try to rebuild `mozc_renderer` with the following modifications to [qt_window_manager.cc](https://github.com/google/mozc/blob/master/src/renderer/qt/qt_window_manager.cc#L89)?

Current code
```cpp
int QtWindowManager::StartRendererLoop(int argc, char **argv) {
  QApplication app(argc, argv);

#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
  QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif
```

Modification1: Swap the order of setAttribute and app initialization. The working GUI tool call them in this order.
```cpp
int QtWindowManager::StartRendererLoop(int argc, char **argv) {
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
  QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif

  QApplication app(argc, argv);
```

Modification2-5: use [setHighDpiScaleFactorRoundingPolicy](https://doc.qt.io/qt-5/qt.html#HighDpiScaleFactorRoundingPolicy-enum) Note, this function is available since Qt 5.14.
```cpp
int QtWindowManager::StartRendererLoop(int argc, char **argv) {
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
  QApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif

  // Uncomment either of them
  QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
  // QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::Ceil);
  // QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::Floor);
  // QGuiApplication::setHighDpiScaleFactorRoundingPolicy(Qt::HighDpiScaleFactorRoundingPolicy::RoudPreferFloor);

  QApplication app(argc, argv);
```

Thank you,

**Comment by jaro3** [comment] 2021-08-09 09:35
Okay, but I don't know how do download and patch the sources from git for makepkg...  Could you please send me the modifications as patches to enter in the prepare() step of the PKGBUILD file?

`## Helpful internal stuff
_commit=87f9ce226a32225cd3dfedde47a21fa16541ae88
_mozcver=2.26.4444.102
_utdicver=20210725

pkgname='ibus-mozc-ut'
pkgver=${_mozcver}.${_utdicver}
pkgrel=1
pkgdesc='Mozc module for IBus bundled with the UT dictionary'
arch=('i686' 'x86_64')
url='https://github.com/google/mozc'
license=('custom')
depends=('ibus>=1.4.1' 'mozc-ut-common')
makedepends=('bazel' 'git' 'pkgconf' 'python-six' 'qt5-base' 'unzip')
conflicts=('ibus-mozc' 'ibus-mozc-ut2' 'ibus-mozc-ut-united')
provides=("ibus-mozc=${_mozcver}")
source=("${pkgname}-git::git+https://github.com/google/mozc.git#commit=${_commit}")
sha256sums=('SKIP')

prepare() {
    cd ${pkgname}-git

    git submodule update --init --recursive

    # Fix the Qt5 include path
    sed -i -e 's/x86_64-linux-gnu\/qt5/qt/' src/config.bzl

    # Fix the GLib include path
    sed -i -e 's/x86_64-linux-gnu\/glib/glib/' src/BUILD.ibus.bazel
}
`

**Comment by kofuk** [comment] 2021-08-10 04:27
I usually use Mozc on 1920x1080 screen, and also have similar problem, and non of them resolved for me (`Mozc-2.26.4458.102+24.10.oss`).
The candidate window doesn't have enough height and is scrollable.

![out](https://user-images.githubusercontent.com/23480349/128807938-abc02296-66c9-40bc-aec0-ee8f8f522994.png)

**Comment by hiroyuki-komatsu** [comment] 2021-08-15 14:46
Hi jaro3, I'm not familiar with PKGBUILD, but I guess the following steps might work:

1. copy [qt_window_manager.cc](https://github.com/google/mozc/blob/master/src/renderer/qt/qt_window_manager.cc) to /tmp (or somewhere).
2. modify `/tmp/qt_window_manager.cc` as in [the above comment](https://github.com/google/mozc/issues/514#issuecomment-894765923).
3. modify PKGBUILD as follows:

```
git submodule update --init --recursive

# Modify qt_window_manager.cc
cp /tmp/qt_window_manager.cc src/renderer/qt/qt_window_manager.cc

# Fix the Qt5 include path
sed -i -e 's/x86_64-linux-gnu\/qt5/qt/' src/config.bzl

# Fix the GLib include path
sed -i -e 's/x86_64-linux-gnu\/glib/glib/' src/BUILD.ibus.bazel
```

4. Build a package with PKGBUILD


Hi kofuk, thank you for sharing your situation. It is helpful to confirm this issue is not a problem on a single environment. Would you please tell me the following things too?

* Whether the fractional scaling is used or not (e.g. yes if your scaling is 150%, 125%, but not 100% or 200%).
* Your platform (e.g. Ubuntu).

Thank you,

**Comment by jaro3** [comment] 2021-08-15 16:58
Okay, I have to learn the PKGBUILD system.  First of all, would this be the correct patch?   The qt_window_manager.cc code is more complex than you wrote:
[qt_window_manager.patch.txt](https://github.com/google/mozc/files/6988524/qt_window_manager.patch.txt)

**Comment by kofuk** [comment] 2021-08-16 04:20
I encountered the problem on

- No fractional scaling on stock GNOME Shell and Mutter (not x11 scaling patch-applyed one)
- Arch Linux

(I'll create new issue entry if you think this is separated problem.)

**Comment by hiroyuki-komatsu** [comment] 2021-08-22 16:57
Hi jaro3,

Your attached file `qt_window_manager.patch.txt` seems to contains HTML tags like:
```
--- qt_window_manager1.cc	2021-08-16 01:48:06.676288470 +0900
+++ qt_window_manager.cc	2021-08-16 01:24:22.642630101 +0900
@@ -1490,27 +1490,29 @@
       </tr>
       <tr>
         <td id="L90" class="blob-num js-line-number" data-line-number="90"></td>
-        <td id="LC90" class="blob-code blob-code-inner js-file-line">#<span class="pl-k">if</span> (QT_VERSION &gt;= QT_VERSION_CHECK(5, 6, 0))</td>
+        <td id="LC90" class="blob-code blob-code-inner js-file-line">  QApplication <span class="pl-smi">app</span>(argc, argv);</td>
...
```

The code I wrote in https://github.com/google/mozc/issues/514#issuecomment-894765923 is a part of qt_window_manager.cc from [Line 89](https://github.com/google/mozc/blob/master/src/renderer/qt/qt_window_manager.cc#L89). Please modify that part of qt_window_manager.cc as I wrote.

Here is a patch for Modification1 [renderer_app_order.patch.txt](https://github.com/google/mozc/files/7027767/renderer_app_order.patch.txt)

**Comment by hiroyuki-komatsu** [comment] 2021-08-22 17:01
Hi kofuk,

Would you try this patch on you environment?

[renderer_single_widget.patch.txt](https://github.com/google/mozc/files/7027769/renderer_single_widget.patch.txt)

(Let's keep using this issue at this moment. I'm not sure it's the same problem or not yet.)

**Comment by kofuk** [comment] 2021-08-22 23:42
Hi,

Thank you for your effort.
But after applying the patch, *still* have the same problem.

![](https://user-images.githubusercontent.com/23480349/130373513-25d389bd-a7dd-4ebc-aa3f-6b0f0891e195.png)

**Comment by jaro3** [comment] 2021-08-23 09:20
OK got the build with your qt_window_manager.cc patches.  Now it seems better - got to the point as kofuk.  The selection window is longer but still cuts in the middle of a line....

**Comment by hiroyuki-komatsu** [comment] 2021-08-23 15:34
Thank you for checking it. It is very helpful for me.

Then, while keeping that patch, please try changing the value of `kRowHeight` from 20 to others (e.g. 24).

https://github.com/google/mozc/blob/master/src/renderer/qt/qt_window_manager.cc#L43

If this works, I will modify the logic to adjust `kRowHeight` based on the font size.

**Comment by jaro3** [comment] 2021-08-24 06:56
Yes, works!  The selection window last row is no longer cut at half with the value of 24.  Thank you.

![MVIMG_20210824_154924s](https://user-images.githubusercontent.com/12386887/130570855-67d90585-406a-4077-84be-406dc1165ea4.jpg)

**Comment by jaro3** [comment] 2021-08-25 12:09
Only one thing, the selection window is quite apart from the input window and cannot be moved.....

**Comment by hiroyuki-komatsu** [comment] 2021-08-28 14:58
d455bc33f831049b8860d64ddfb4ce5f189d1e91 (BUILD=4479) added the above patches and logic to adjust the height based on the font size.

I'm going to close this bug. Please let me know if this still doesn't work for you.

For other issues (e.g CPU usage, window position, etc.), please feel free to make new issues.
Thank you very much for your reports.

**Closed** 2021-09-05 04:22 UTC

**Comment by jaro3** [comment] 2021-09-05 16:45
Ha, compiled the latest updated version from AUR and the problem is back :-(
Mozc-2.26.4472.102+24.10.oss

https://aur.archlinux.org/packages/?O=0&K=mozc
