### ISSUE TITLE
mocz_tool with fatal errors (debian jessie)

### ISSUE THREAD

**Issue by otyu** [google/mozc#387] opened 2016-09-27 05:06 UTC
Using debian jessie. Recently installed packages `mozc-data, mozc-server, mozc-utils-gui, uim-mozc`.

I have problems using `/usr/lib/mozc/mozc_tool` with some modes, e.g. `-mode=dictionary_tool`, `--mode=word_register_dialog`, `--mode=character_palette`. It gives me the following errors.

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: session/candidates.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
Aborted
```

I hope this has a fix. Thank you.

**Comment by yukawa** [comment] 2016-09-27 05:38
Thank you for the report.

I believe this is a duplicate of #14, which was already fixed in Mozc upstream but not fixed yet in Debian package due to Debian's packaging policy. Thus I would suggest you report this to [Debian bug 700307](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700307) and/or [Debian bug 721791](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=721791) instead, or report this to protobuf team at google/protobuf#1941, because to fix this we have to change either 1) how Mozc is packaged in Debian or 2) how protobuf library works when being used as a dynamic library.

**Closed by yukawa** 2016-09-27 05:38 UTC
