### ISSUE TITLE
GTK+3 support for mozc_renderer

### ISSUE THREAD

**Issue by m-shibata** [google/mozc#456] opened 2018-11-10 06:43 UTC
mozc_renderer with `--enable-gtk-renderer` is built for gtk+-2.0, could you support gtk+3?

This is not a bug, mozc_render well work with gtk+-2.0, just feature request.

**Comment by hiroyuki-komatsu** [comment] 2020-12-29 09:43
Duplicate of #492

**Closed by hiroyuki-komatsu** 2020-12-29 09:43 UTC
