### ISSUE TITLE
mozc_renderer consumes 100% CPU core after using some time

### ISSUE THREAD

**Issue by kirameister** [google/mozc#520] opened 2021-09-10 21:06 UTC
Dear mozc team, 

I've been experiencing `mozc_renderer` process consuming 100% CPU usage after using mozc for some time (5-10 minutes, perhaps?). 

Please find the attached log files: 
* [mozc_renderer.log](https://github.com/google/mozc/files/7146417/mozc_renderer.log)
* [mozc_server.log](https://github.com/google/mozc/files/7146418/mozc_server.log)
* [ibus-engine-mozc.log](https://github.com/google/mozc/files/7146430/ibus-engine-mozc.log)

Following is the steps I took to create those log files: 
1. Install the latest version of mozc
2. Make sure that log-level is set to `2`
3. Remove all the log files by running `rm -f $HOME/.mozc/*.log`
4. Reboot the machine
5. Use mozc for some time (until the fan starts to scream = high CPU usage)
6. Ensure that the `mozc_renderer` process is indeed consuming 100% of a single CPU core
7. Copy those log files so that (hopefully) the real issue could be found towards the bottom of the file(s). 

The version of the mozc is: Mozc-2.26.4486.102+24.10.oss

Please note the following: 
* By "100% CPU usage", I meant "100% CPU usage of a single CPU core". I.e., `mozc_renderer` was only consuming one of the CPU cores available in my machine up to 100%; the remaining CPU cores didn't seem to be used. 
* FWIW, I'm using Pop!_OS as my environment, but I've observed the same behavior in my Ubuntu VM: 
```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

I'd greatly appreciate it if you could have a look at this issue. In case any further input / information is required from my end, I'd be more than happy to provide it. 

Best regards,
Akira K.

**Comment by hiroyuki-komatsu** [comment] 2021-09-12 12:08
Hi Akira,
Thank you for your report with logs.

We understand the current renderer has the CPU 100% consumption issue on several environments.
However my environment doesn't have this problem, so it's difficult to debug it.

Qt based Mozc renderer uses two thread libraries (pthread and Qthread).
I'm wondering this might be the root cause.

Do you always have this problem? Or does this only happen when you type specific characters, or when you use specific applications?

Here are two temporary workarounds for you:
* Use the default Ibus candidate window.
  + remove mozc_renderer from the installed path.
  + `rm /usr/lib/mozc/mozc_renderer`
* Use the previous GTK2 based candidate window.
  + `bazel build renderer:gtk_mozc_renderer -c opt`
  + copy and rename the built `gtk_mozc_renderer` to `/usr/lib/mozc/mozc_renderer`.

Thanks,

**Comment by kirameister** [comment] 2021-09-17 23:17
Dear Hiroyuki-san, 

Thank you very much for your reply, as always!

I wasn't aware that mozc still works without `mozc_renderer`. It's been few days since I removed `/usr/lib/mozc/mozc_renderer`. Apart from the different look&feel, which doesn't affect its functionality, the whole IME seems to be working and without consuming 100% CPU usage. 

While I'm satisfied with this solution (to use default iBus candidate window), I wonder if this issue should be closed or not. While I'm personally completely fine this ticket being closed, I wonder others may be opening another ticket with the same content (as one doesn't always look at the closed issues). Well, I'll leave it up to you to decide either close this ticket, or intentionally keep it "floating around". 

As always, thank you very much for maintaining this project!

Best regards,
Akira K.

**Comment by hiroyuki-komatsu** [comment] 2021-09-18 10:35
Hi Akira-san,
I'm glad to hear the workaround works for you.

Please keep this issue open.

I will try to investigate the root cause.
Thank you,

**Comment by hiroyuki-komatsu** [comment] 2022-02-22 10:51
I performed the whole refactoring to the Qt candidate window.
It has replaced Mozc's thread and mutex in the implementation with Qt's ones.

This issue doesn't happen my environment.
Would you confirm if the build 4656 works or not?

**Comment by kirameister** [comment] 2022-02-23 08:23
Hello Hiroyuki-san, 

Thank you very much for your follow-up! I've built mozc on my local environment and confirmed that it's ばーじょん is "Mozc-2.26.4656.102+24.10.oss". I'll keep playing around with this version (with `mozc_renderer` in place) for a while and get back to you if / when I'd observe the reported behavior.

**Comment by hiroyuki-komatsu** [comment] 2022-03-20 10:09
I close this issue as it seems the latest version works as expected.
Please feel free to reopen it or make a new issue, if this issue happens again.

Thank you for you supports!

**Closed by hiroyuki-komatsu** 2022-03-20 10:09 UTC

**Comment by kirameister** [comment] 2022-03-20 20:48
Hello Hiroyuki-san, 

Thank you very much for your follow-up. Just FYI, I haven't experienced the 100%-CPU-usage behavior after updating the mozc version to `Mozc-2.26.4656.102+24.10.oss`. I see no problem from my end in closing this ticket. 

Best regards,
Akira K.
