### ISSUE TITLE
Unable to import custom keymap for Romaji input Ubuntu20.04

### ISSUE THREAD

**Issue by ngfuwai** [google/mozc#517] opened 2021-09-07 18:22 UTC
Under tools -> properties -> keymap -> romaji table, there is a button called "Customize" which brings up a separate window for editing the keymaps of the romaji table. On the bottom left corner of that window, there is a button called "Edit" which presents a dropdown when clicked. One of the options in the dropdown is "Import from file...." which does not work currently. I have tried to import csv files, txt files, and tsv files, but none seem to work. Importing a new file only wipes clean the current romaji table without any change to the actual key mappings. 

![image](https://user-images.githubusercontent.com/17035550/132393540-8798c13b-9a40-4b80-9123-2607272d8f8d.png)
![image](https://user-images.githubusercontent.com/17035550/132393608-12284aa4-7dba-4417-a834-12696c6aba16.png)
![image](https://user-images.githubusercontent.com/17035550/132393630-1096ed86-1092-4359-bc91-62543fcf2b6b.png)
![image](https://user-images.githubusercontent.com/17035550/132393759-1a8b79bc-6aad-4171-a13f-86768fcd9049.png)

**Comment by hiroyuki-komatsu** [comment] 2021-09-11 07:24
Hi Tiger,
Thank you for your report with sceenshots. It's helpful to understand the situation.

Would you try the following steps?

1. Open Mozc Romaji table editor.
2. Reset to defaults.
3. Select "Export to file" and get an exported file.
4. Select "Import from file" and specify the exported file.

FYI. The supported format is TSV with 3 columns.

**Comment by ngfuwai** [comment] 2021-09-11 18:24
I tried what you suggested, but the export functionality creates a .txt file instead of a .tsv file. I was trying with .csv files and .txt files earlier, so that's why it didn't work. The import functionality does work with .tsv files.

**Comment by hiroyuki-komatsu** [comment] 2021-09-18 10:31
I think the problem was solved. So let me close this issue.

Please feel free to reopen it, if the problem is not solved yet.

**Closed by hiroyuki-komatsu** 2021-09-18 10:31 UTC
