### ISSUE TITLE
ITextStoreACP::GetTextExt() is called with wrong arguments

### ISSUE THREAD

**Issue by masayuki-nakano** [google/mozc#338] opened 2015-12-22 09:36 UTC
At converting a composition string on TSF-aware application on Windows, GetTextExt() is called 3 times. I tested with one character and type spacebar. Then,

1. ITextStoreACP::GetTextExt(acpStart=0, acpEnd=1)
2. ITextStoreACP::GetTextExt(acpStart=1, acpEnd=1)
3. ITextStoreACP::GetTextExt(acpStart=0, acpEnd=1)

I see these calls. The problem is the 2nd call. acpStart and acpEnd is same value (i.e., the length is 0!). In this case, ITextStoreACP::GetTextExt() should return TS_E_INVALIDARG. See MSDN document: https://msdn.microsoft.com/en-us/library/windows/desktop/ms538435%28v=vs.85%29.aspx

So, if the 2nd call is directly caused by mozc (i.e., not by TSF automatically), this is a bug of mozc.

FYI: I tested with Firefox.

**Comment by yukawa** [comment] 2016-01-24 05:16
Thank you for the report, I can reproduce the issue you reported in for following environment.
* Firefox 43.0.2
* Windows 10 (10586.36)
* Mozc-2.17.2262.100

That said, I don't think the 2nd call was made by Mozc. Thus I'd like to close this issue as I think you should report this issue to Microsoft rather than us.  Let me know if you disagree.

## Background
Here is [a detailed sequence graph](https://docs.google.com/spreadsheets/d/1nV5rthnZx3riONgY2VhffQBpYdaKvpkiXBhSG17OsNU/view#gid=0) I made. As for the 1st call of [ITextStoreACP::GetTextExt](https://msdn.microsoft.com/en-us/library/windows/desktop/ms538435.aspx) at line 38, yes I can confirm that it was from [```mozc::win32::tsf::TipRangeUtil::GetTextExt```](https://github.com/google/mozc/blob/cac146508d32fcce1ecfec8d038f63f588ed13c4/src/win32/tip/tip_range_util.cc#L226-L261), which internally calls [```ITfContextView::GetTextExt```](https://msdn.microsoft.com/en-us/library/windows/desktop/ms538782.aspx). However, the 2nd call at line 53 was not ours.  It was made by ```tiptsf.dll!CCorrectionIMX::_GenerateCaretEvents```, which is apparently developed by Microsoft.  I think this is something that should be fixed in TSF runtime.

That said, given that this was from a method named ```CCorrectionIMX::_GenerateCaretEvents```, looks like Microsoft has intentionally been calling ```ITextStoreACP::GetTextExt(acpStart=1, acpEnd=1)``` for something related to Caret rectangle. Thus I'd suggest treating this API call as a valid request in Firefox rather than rejecting API calls from a system component as an invalid call.

Thanks,

**Closed by yukawa** 2016-01-24 05:16 UTC
