### ISSUE TITLE
How to use preferences and misc?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#210] opened 2015-04-22 07:54 UTC
```
Hi, I've finished to compile mozc on MacOS X (10.9). I followed document and 
Now I could type Mozc(They're pretty cool I guess). But how to use like Mozc 
Preferences and others? Please let me know. I'm bad if I miss docs or some 
reports.
```

Original issue reported on code.google.com by `ynzfm...@gmail.com` on 1 Apr 2014 at 7:29

**Comment by oldergod** [comment] 2016-02-08 00:56
No update on this? I could not either open the preferences, the "add a word", dictionary tool etc. Is there a proper way to do this?

**Comment by yukawa** [comment] 2016-02-08 22:21
If you have built Mozc with ```--noqt```, then you cannot use them since those features depends on Qt. The proper way is to build Mozc with Qt. I'm not sure if building OSS Mozc with Qt is well supported/tested in the latest version though.

**Comment by oldergod** [comment] 2016-02-09 00:47
Thank you. Would there be another way to set those conf via shell?

**Comment by yukawa** [comment] 2016-02-09 01:11
Unfortunately there is no alternative way, especially in command line.  An unofficial but easy work around would be to build ```mozc_tool``` (or just ```apt-get install mozc-utils-gui```) and configure the settings on Ubuntu, then copy ```~/mozc/config1.db``` from there to your system.

To be precise It's technically possible to read and write our config file in command line because our config file is just a serialized byte stream of [```src/protocol/config.proto```](https://github.com/google/mozc/blob/4a370c6ea6f003be99e7837713a939a68b75aeae/src/protocol/config.proto). You can do whatever you want with [Protocol Buffers APIs](https://developers.google.com/protocol-buffers/docs/reference/overview) and [data format](https://developers.google.com/protocol-buffers/docs/encoding).

**Comment by oldergod** [comment] 2016-02-09 01:38
I was mostly interested in the user dictionary. I copied `~/.mozc/config1.db` and `~/.mozc/user_dictionary.db` to my `~`, and reboot but does not seem to work at the moment.

I'll give the Qt way a try.

**Comment by yukawa** [comment] 2016-02-09 02:07
>  I copied ```~/.mozc/config1.db``` and ```~/.mozc/user_dictionary.db``` to my ```~```, and reboot but does not seem to work at the moment.

Sorry, I wasn't clear about that. The profile directly varies depending on platforms.  I haven't confirmed it, but for OS X I guess the location you want to put those files is ```~/Library/Application Support/Mozc/```, not ```~/.mozc/```, which is true for Linux platforms.

 - [```src/base/config_file_stream.cc```](https://github.com/google/mozc/blob/4a370c6ea6f003be99e7837713a939a68b75aeae/src/base/config_file_stream.cc#L113-L124)
 - [```src/base/system_util.cc```](https://github.com/google/mozc/blob/4a370c6ea6f003be99e7837713a939a68b75aeae/src/base/system_util.cc#L232)
 - [```src/base/mac_util.mm```](https://github.com/google/mozc/blob/4a370c6ea6f003be99e7837713a939a68b75aeae/src/base/mac_util.mm#L126-L136)

Keep in mind that these things are subject to change.

**Comment by oldergod** [comment] 2016-02-09 02:25
I don't know OS X that much yet so thank you for the explanation. I got it working fine now.

> Keep in mind that these things are subject to change. We never encourage users to rely on these implementation details.

Of course ! And thank you for mozc, by far the best japanese IME I know.

**Comment by yukawa** [comment] 2016-11-21 05:01
Anyway I'm going to close this as the original report was that the reporter built Mozc with `--noqt`. Not being able to use GUI tools is WAI in such a scenario.  To make those tools work, please make sure to build Mozc with Qt by following the instructions in [GUI tools section](https://github.com/google/mozc/blob/8aa3f5691b7a1a7cb9df03545ba85c8b2d58c70c/docs/build_mozc_in_osx.md#gui-tools) of the build instruction.

**Closed by yukawa** 2016-11-21 05:01 UTC
Labels: auto-migrated, OpSys-OSX, Priority-Low, Type-Defect
