### ISSUE TITLE
"any"で始まる文字列を入力すると"any"部分が消える

### ISSUE THREAD

**Issue by unitedstar-tech** [google/mozc#762] opened 2023-06-17 03:14 UTC
**Description**
"any"で始まる文字列を入力すると"any"部分が消える

**Steps to reproduce**
1. ひらがな入力モードで"any"から始まる文字列を入力する(e.g. anytime)
2. "any"の部分が消失し、後続の文字列が入力される

**Expected behavior**
"any"を含めた文字列が入力される

**Actual behavior**
"any"で始まる文字列を入力すると"any"部分が消える

**Screenshots**

https://github.com/google/mozc/assets/16453541/ca756d88-c430-452d-acee-412c0b7d77c6

**Version or commit-id**
[e.g. Mozc-2.28.4960.100+24.11.oss or d50a8b9ae28c4fba265f734b38bc5ae392fe4d25]
You can get the version string by converting "Version" or "ばーじょん".

**Environment**
 - OS: Fedora38 Workstation
 - IMF (for Linux) : Ibus

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + N/A
 - What applications this issue happens on (e.g. Chromium, gedit).
   + Anything
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + N/A
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + N/A

**Additional context**
Add any other context about the

 problem here.

**Comment by hiroyuki-komatsu** [comment] 2023-07-16 11:23
Hi unitedstar-tech,
Thank you for your feedback. The screen record is helpful for us to see the behavior.

We were not able to reproduce your problem. When we typed "anytime", it was composed to "あｎｙちめ" as expected.

Would you confirm the following things?

* If you have customized some preferences especially the Romaji table and the halfwidth/fullwidth settings, would you confirm it with the default settings?
* If you use an old version of Mozc, would you try to use the latest version of the GitHub repository?

Thank you,

**Comment by unitedstar-tech** [comment] 2023-08-08 03:47
Hi hiroyuki-komatsu,

> If you have customized some preferences especially the Romaji table and the halfwidth/fullwidth settings, would you confirm it with the default settings?

Here are the screen capture of halfwidth/fullwidth settings and the Romaji table.
![screen](https://github.com/google/mozc/assets/16453541/c8409fc1-8dc6-4be6-acc5-4651cb201618)
[romantable.txt](https://github.com/google/mozc/files/12287043/romantable.txt)

> If you use an old version of Mozc, would you try to use the latest version of the GitHub repository?

I'm using following version of Mozc.
- mozc-2.28.4950.102-7.fc38.x86_64
- ibus-mozc-2.28.4950.102-7.fc38.x86_64

Thank you.

**Comment by hiroyuki-komatsu** [comment] 2023-08-16 05:32
Hi unitedstar-tech,
I was not able to reproduce your issue with your configuration in the latest build.

The recent change [google/mozc@00082dd](https://github.com/google/mozc/commit/00082dd77eea4c5506a90284ece2f6357ef64ad0) perhaps addressed this issue.

Would you try a newer version (i.e. 2.29.5185) with the above change?
Thank you,

**Comment by hiroyuki-komatsu** [comment] 2023-10-16 04:24
Closing this issue.

Please feel free to reopen it, if a newer version has not fixed this issue.
Thank you,

**Closed by hiroyuki-komatsu** 2023-10-16 04:24 UTC
