### ISSUE TITLE
Becomes inactive on Google Docs, Slides

### ISSUE THREAD

**Issue by 130s** [google/mozc#297] opened 2015-08-25 20:27 UTC
First of all, thanks for the great tool!

Mozc becomes inactive frequently on my Google Docs and Slides. 
- The Mozc indicator on the desktop's bar seems still active with Mozc, but conversion doesn't happen as if I were typing in no-conversion mode. 
- Once it starts to happen, turning on and off the conversion mode of the OS doesn't seem to help.
 - However, after awhile (not determined period) when I got back to the same page, I often see Mozc is back active.
- My temporary dumn workaround is to reload the page, which so far has always worked.

```
Ubuntu 14.04
Google Chrome	44.0.2403.157 (Official Build) (64-bit)
Revision	4d31269c6cafb98eced74df70f5d1ccde3af0a44-refs/branch-heads/2403@{#614}
OS	Linux 
Blink	537.36 (@200670)
JavaScript	V8 4.4.63.31
Flash	18.0.0.233
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
```
Let me know if you need more data.

**Comment by yukawa** [comment] 2015-08-25 20:38
Thank you for the report.  I suspect that this is a duplicate of [Chromium Issue 449601](https://code.google.com/p/chromium/issues/detail?id=449601).

Can you leave a comment at [Chromium Issue 449601](https://code.google.com/p/chromium/issues/detail?id=449601) with following information?
* Input method you are using. [[ibus, uim, fcitx, uim]]
* Version of Mozc.

I'm going to close this issue since I suppose the issue you are suffering from is also reproducible with other input methods hence it should be addressed in Chromium side.

Thanks!

**Closed** 2015-08-25 20:38 UTC

**Comment by 130s** [comment] 2015-08-26 00:40
Reporting to browser sounds reasonable (since this only happens on Chrome afaik), so I made one. Thank you.
